# Generated by Django 5.2.7 on 2025-12-19 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_match', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Imię zwierzaka.', max_length=50, verbose_name='Imie pupila')),
                ('pet_type', models.CharField(choices=[('', '--- Nic / Nie Wybrano ---'), ('P', 'Pies'), ('K', 'Kot'), ('G', 'Gryzoń'), ('B', 'Ptak'), ('R', 'Ryba'), ('H', 'Koń'), ('J', 'Jaszczur'), ('I', 'Inne')], default='', help_text='Typ zwierzaka, np. Pies, Kot.', max_length=1)),
                ('breed', models.CharField(blank=True, help_text='Rasa pupila (jeśli dotyczy).', max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Waga pupila w kg', max_digits=5, null=True)),
                ('description', models.TextField(blank=True, help_text='Krótki opis charakteru pupila.')),
                ('is_friendly', models.BooleanField(default=True, help_text='Czy pupil jest przyjazny i lubi towarzystwo?')),
                ('age', models.PositiveSmallIntegerField(default=1, help_text='Wiek pupila w latach.')),
            ],
            options={
                'verbose_name': 'Pupil',
                'verbose_name_plural': 'Pupile',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Adres email (login)', max_length=254, unique=True)),
                ('password', models.CharField(editable=False, max_length=128)),
                ('avatar', models.ImageField(blank=True, help_text='Zdjecie profilowe', null=True, upload_to='avatars')),
                ('birth_date', models.DateField(blank=True, help_text='Data urodzenia', null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('city', models.CharField(help_text='Miasto, w którym mieszkacie (Ty i Twój pupil).', max_length=50)),
                ('gender', models.IntegerField(choices=[(1, 'Kobieta'), (2, 'Mężczyzna'), (3, 'Inna'), (4, 'Nie'), (5, 'Podano')], default=1, help_text='Płeć.')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data rejestracji')),
                ('preferred_pet_type', models.CharField(blank=True, choices=[('', '--- Nic / Nie Wybrano ---'), ('P', 'Pies'), ('K', 'Kot'), ('G', 'Gryzoń'), ('B', 'Ptak'), ('R', 'Ryba'), ('H', 'Koń'), ('J', 'Jaszczur'), ('I', 'Inne')], default='', help_text='Jakiego puila szukasz u potencjalnego partnera.', max_length=1)),
                ('bio', models.TextField(blank=True, help_text='Krótki opis o Was (Ty i Twój Pupil) i o tym, kogo szukasz.')),
                ('pets', models.ManyToManyField(blank=True, help_text='Wszystkie pupile przypisane do tego profilu.', to='aplikacja.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Treść wiadomości.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(help_text='Wiadomość powiązana z konkretnym dopasowaniem.', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='aplikacja.match')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='aplikacja.userprofile', verbose_name='Odbiorca')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='aplikacja.userprofile', verbose_name='Nadawca')),
            ],
            options={
                'verbose_name': 'Wiadomość',
                'verbose_name_plural': 'Wiadomości',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='swiper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_likes', to='aplikacja.userprofile', verbose_name='Polubił'),
        ),
        migrations.AddField(
            model_name='match',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_likes', to='aplikacja.userprofile', verbose_name='Polubiony'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('swiper', 'target')},
        ),
    ]
