# Generated by Django 5.2.7 on 2026-01-29 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0002_remove_userprofile_email_remove_userprofile_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='aplikacja.match'),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='aplikacja.userprofile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='aplikacja.userprofile'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.PositiveSmallIntegerField(default=1, help_text='Wiek.'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, help_text='Rasa pupila.', max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.TextField(blank=True, help_text='Opis pupila.'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='is_friendly',
            field=models.BooleanField(default=True, help_text='Czy przyjazny?'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(choices=[('', '--- Nic / Nie Wybrano ---'), ('P', 'Pies'), ('K', 'Kot'), ('G', 'Gryzoń'), ('B', 'Ptak'), ('R', 'Ryba'), ('H', 'Koń'), ('J', 'Jaszczur'), ('I', 'Inne')], default='', help_text='Typ zwierzaka.', max_length=1),
        ),
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Waga w kg', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Kobieta'), (2, 'Mężczyzna'), (3, 'Inna'), (4, 'Nie podano')], default=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pets',
            field=models.ManyToManyField(blank=True, to='aplikacja.pet'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_pet_type',
            field=models.CharField(blank=True, choices=[('', '--- Nic / Nie Wybrano ---'), ('P', 'Pies'), ('K', 'Kot'), ('G', 'Gryzoń'), ('B', 'Ptak'), ('R', 'Ryba'), ('H', 'Koń'), ('J', 'Jaszczur'), ('I', 'Inne')], default='', max_length=1),
        ),
    ]
